### ISSUE TITLE
Name Change

### ISSUE THREAD

**Issue by ccoffrin** [Wikunia/Juniper#55]
Some ideas for a better name,

nonlinear branch and bound (optimizer):
- NLBB (short and sweet)
- NLOPT (pronounceable, discrete support is unclear, [name clash](https://github.com/stevengj/nlopt))
- NLBBOPT (no vowels makes it hard to say)
- NLBOP (easy to say, but makes me think of mmmbop)

heuristic nonlinear branch and bound (optimizer):
- HNLBB (more accurate, no vowels makes it hard to say)
- HeNLBB (still hard to stay)
- HuNoBB (easier to say, sounds like GuRoBi, could be misleading as no global opt guarante)
- HNOPT (similar to SNOPT, KNITRO, discrete support is unclear)
- HLNOPT (said HNL-OPT, discrete support is unclear)

(heuristic) mixed integer nonlinear (optimizer):
- MINOPT ([name clash](https://titan.princeton.edu/MINOPT), probably trademarked)
- HEMINOPT (said HEMIN-OPT or just HEMIN)

(heuristic) discrete nonlinear (optimizer):
- DNOPT (similar to SNOPT, KNITRO)
- DINLOPT (sounds like dunlop...)
- HEDINOL (anti-pain medication, could be some good jokes there)
- HEDINOPT (said HEDIN-OPT or just HEDIN, [note mythology](https://en.wikipedia.org/wiki/Hedin))

**Comment by ccoffrin** [comment]
additional suggestions and top-picks would be much appreciated, @jac0320, @kaarthiksundar, @harshangrjn, @rb004f, @hhijazi, @mlubin.

**Comment by Wikunia** [comment]
Some more suggestions based on the branch and bound tree part.

- Trinear (Short for Tree and non linear)
- Nogal (Tree in New Mexico and **No**nlinear)

Abbreviations
- NARD (**N**online**a**r **R**oot **D**iscrete)
- NATRON (**N**online**a**r **Tr**ee **O**ptimizatio**n**)
- BACON (**B**r**a**n**c**h **O**ptimization **N**onlinear)

**Comment by konstantinkobs** [comment]
Some additional, more or less short, but very pronounceable names:

- DiNoLi OptiBound (**Di**screte **No**n-**Li**near **Opti**mizer using Branch and **Bound**)
- DiNoLiBound
- DiNoLiBo

I like how these names have _Dino_ in it, which could lead to a logo containing a dinosaur. :smile:

**Comment by shibumi** [comment]
I would go for BACON (Branch Optimization Nonlinear)

**Comment by Wikunia** [comment]
The C in BACON could also stand for customizable. As you can use any non linear solver in the background and have more control over the solver using the options.

**Comment by hhijazi** [comment]
Not a big fan of BACON..it can give you cancer :)

**Comment by hhijazi** [comment]
JUBB: Julia B&B

**Comment by Wikunia** [comment]
BOREDOM (**B**ranch and B**o**und T**re** **D**iscrete **O**pti**m**ization ) 
Reminds me of the [Boring Company](https://www.boringcompany.com)

**Comment by Wikunia** [comment]
It's just too much fun...
NETON (NonlinEar Tree Optimization Nonlinear) 
Reminds me of Newton, which gives a hint to Interior Point (okay only for IPOpt) and also for the famous tree in Newton's life.

**Comment by ccoffrin** [comment]
I kinda like BACON :-) 

The nonlinear aspect does not make it into BOREDOM.

JuBB is a nice way to get a vowel, Ju could also stand for JuMP, which is more specific that Julia.

**Comment by ccoffrin** [comment]
JUNIPER - JUmp Nonliner Integer Program solvER, kind of plays into the south west mountain theme.

**Comment by Wikunia** [comment]
Maybe trademarked? https://www.juniper.net/us/en/

**Comment by ccoffrin** [comment]
Probably "juniper networks" is, but the names of a plants are in the public domain, https://en.wikipedia.org/wiki/Juniper.

**Comment by shibumi** [comment]
You can also call it "the ugly name project'. Than at least everybody would instantly ask you out about it.

**Comment by Wikunia** [comment]
We decided to name it Juniper (Jump Nonlinear Integer Program solver)
